var createError = require("http-errors");
var express = require("express");
var path = require("path");
var cookieParser = require("cookie-parser");
var morgan = require("morgan");
const { SetMongo } = require("./routes/controller/mongoose");
const cors = require("cors");
const { eventlogger, logger } = require("./middleware/logger");
const cron = require("node-cron");
const { insertDailyAttendanceStatus } = require("./routes/repository/attendance_status");
const swaggerDocs = require('./document/swagger');
const swaggerUi = require('swagger-ui-express');

// Schedule the function to run every day at 23:59 (11:59 PM)
cron.schedule("0 0 * * *", () => {
  console.log("Running daily attendance status insertion...");
  insertDailyAttendanceStatus();
});

//#region ROUTES IMPORT
var indexRouter = require("./routes/index");
var usersRouter = require("./routes/users");
var employeeRouter = require("./routes/employee");
var employeeprofileRouter = require("./routes/employeeprofile");
var departmentRouter = require("./routes/department");
var allleaveRouter = require("./routes/allleave");
var pendingleaveRouter = require("./routes/pendingleave");
var approvedleaveRouter = require("./routes/approvedleave");
var rejectedleaveRouter = require("./routes/rejectedleave");
var attendanceRouter = require("./routes/attendance");
var shiftRouter = require("./routes/shift");
var trainingsRouter = require("./routes/trainings");
var positionRouter = require("./routes/position");
var disciplinaryRouter = require("./routes/disciplinary");
var disciplinaryactionRouter = require("./routes/disciplinaryaction");
var offensesRouter = require("./routes/offenses");
var violationRouter = require("./routes/violation");
var healthrecordRouter = require("./routes/healthrecord");
var govermentidRouter = require("./routes/govermentid");
var performanceRouter = require("./routes/performance");
var holidayRouter = require("./routes/holiday");
var holidayrateRouter = require("./routes/holidayrate");
var ojtRouter = require("./routes/ojt");
var announcementRouter = require("./routes/announcement");
var settingsRouter = require("./routes/settings");
var eportalsettingsRouter = require("./routes/eportalsettings");
var accessRouter = require("./routes/access");
var salaryRouter = require("./routes/salary");
var requestcashadvanceRouter = require("./routes/requestcashadvance");
var resignedRouter = require("./routes/resigned");
var deductionRouter = require("./routes/deduction");
var eportalindexRouter = require("./routes/eportalindex");
var eportalrequestleaveRouter = require("./routes/eportalrequestleave");
var eportaldisciplinaryactionRouter = require("./routes/eportaldisciplinaryaction");
var eportalprofileRouter = require("./routes/eportalprofile");
var eportalsalaryRouter = require("./routes/eportalsalary");
var eportalcashadvanceRouter = require("./routes/eportalcashadvance");
var eportalcoopRouter = require("./routes/eportalcoop");
var eportalpayslipRouter = require("./routes/eportalpayslip");
var eportalattendancelayoutRouter = require("./routes/eportalattendance");
var loginlayoutRouter = require("./routes/login");
var candidateRouter = require("./routes/candidate");
var loanRouter = require("./routes/loan");
var paymentRouter = require("./routes/payment");
var interestRouter = require("./routes/interest");
var depositRouter = require("./routes/deposit");
var memberRouter = require("./routes/member");
var registerRouter = require("./routes/register");
var ojtuserRouter = require("./routes/ojtuser");
var geofencesettingsRouter = require("./routes/geofencesettings");
var salaryhistoryRouter = require("./routes/salaryhistory");
var payslipRouter = require("./routes/payslip");
var generatepayrollRouter = require("./routes/generatepayroll");
var apprenticeRouter = require("./routes/apprentice");
var ojtindexRouter = require("./routes/ojtindex");
var ojtloginRouter = require("./routes/ojtlogin");
var ojtattendanceRouter = require("./routes/ojtattendance");
var ojtprofileRouter = require("./routes/ojtprofile");
var ojtreqabsentRouter = require("./routes/ojtreqabsent");
var attendanceojtRouter = require("./routes/attendanceojt");
var appsdetailsRouter = require("./routes/appsdetails");
var otapprovalRouter = require("./routes/otapproval");
var healthcarddeductionsRouter = require("./routes/healthcarddeductions");
var healthcarddeductionsIDRouter = require("./routes/healthcarddeductionsID");
var attendancerequestRouter = require("./routes/attendancerequest");
var eportalrequestattendanceRouter = require("./routes/eportalrequestattendance");
var setsetpayrolldateRouter = require("./routes/setpayrolldate");
var eportalrequestovertimeRouter = require("./routes/eportalrequestovertime");
var teamleadindexRouter = require("./routes/teamleadindex");
var teamleadloginRouter = require("./routes/teamleadlogin");
var teamleademployeeRouter = require("./routes/teamleademployee");
var teamleadcoaRouter = require("./routes/teamleadcoa");
var teamleadovertimeRouter = require("./routes/teamleadovertime");
var teamleadleaveRouter = require("./routes/teamleadleave");
var teamleadusersRouter = require("./routes/teamleadusers");
var teamleadpendingcoaRouter = require("./routes/teamleadpendingcoa");
var teamleadapprovedcoaRouter = require("./routes/teamleadapprovedcoa");
var teamleadappliedovertimeRouter = require("./routes/teamleadappliedovertime");
var teamleadapprovedovertimeRouter = require("./routes/teamleadapprovedovertime");
var teamleadpendingleaveRouter = require("./routes/teamleadpendingleave");
var teamleadapprovedleaveRouter = require("./routes/teamleadapprovedleave");
var teamleadattendanceRouter = require("./routes/teamleadattendance");
var teamleadgeofenceRouter = require("./routes/teamleadgeofence");
var shiftsettingsRouter = require("./routes/shiftsettings");
var empbackgroundRouter = require("./routes/empbackground");
var leavesettingsRouter = require("./routes/leavesettings");
var approval_stage_settingsRouter = require("./routes/approval_stage_settings");
var request_approval_settingsRouter = require("./routes/request_approval_settings");
var subgroupRouter = require("./routes/subgroup");
var attendance_request_activityRouter = require("./routes/attendance_request_activity");
var leave_request_activityRouter = require("./routes/leave_request_activity");
var accessroutelayoutRouter = require("./routes/accessroutelayout");
var bankRouter = require("./routes/bank");
var bankaccountRouter = require("./routes/bankaccount");
var overtime_request_activityRouter = require("./routes/overtime_request_activity");
var supervisoruserRouter = require("./routes/supervisoruser");
var change_shiftRouter = require("./routes/change_shift");
var eportalotmealRouter = require("./routes/eportalotmeal");
var payroll_adjustmentsRouter = require("./routes/payroll_adjustments");
var teamleadappliedotmealRouter = require("./routes/teamleadappliedotmeal");
var meal_request_activityRouter = require("./routes/meal_request_activity");
var teamleadshiftRouter = require("./routes/teamleadshift");
var teamleadshiftadjustmentRouter = require("./routes/teamleadshiftadjustment");
var mobileAPIRouter = require("./routes/mobile-api");
var gov_loansRouter = require("./routes/gov_loans");
var teamleadsettingsRouter = require("./routes/teamleadsettings");
var sidebarRouter = require("./routes/sidebar");
var medecinesRouter = require("./routes/medecines");
var medecinesrequestRouter = require("./routes/medecines_request");
var examRouter = require("./routes/exam");
var question_typeRouter = require("./routes/question_type");
var questionRouter = require("./routes/question");
var ratingRouter = require("./routes/rating");
var teamleadgeofenceempRouter = require("./routes/teamleadgeofenceemp");
var applicant_registrationRouter = require("./routes/applicant_registration");
var eportalrequestHolidayRouter = require("./routes/eportalrequestholiday");
var teamleadholidayRouter = require("./routes/teamleadholiday");
var teamleadtotalholidayRouter = require("./routes/teamleadtotalholiday");
var holiday_request_activityRouter = require("./routes/holiday_request_activity");
var loan_typeRouter = require("./routes/loan_type");
var employer_contributionRouter = require("./routes/employer_contribution");
var sudden_deductionsRouter = require("./routes/sudden_deductions");
var generate13thmonthRouter = require("./routes/generate13thmonth");
var usersubgrouplayoutRouter = require("./routes/usersubgroup");
var eportalgovloansRouter = require("./routes/eportalgovloans");
var forgotpasswordRouter = require("./routes/forgotpassword");
var enrolled_bank_accRouter = require("./routes/enrolled_bank_acc");
var eportalrestdayotRouter = require("./routes/eportalrestdayot");
var restdayot_request_activityRouter = require("./routes/restdayot_request_activity");
var teamleadappliedrdotRouter = require("./routes/teamleadappliedrdot");
var teamleadapprovedrdotRouter = require("./routes/teamleadapprovedrdot");
var retropayRouter = require("./routes/retropay");
var staffhouseRouter = require("./routes/staffhouse");
var staffhouseoccupantRouter = require("./routes/staffhouseoccupant");
var occupantdurationsettingRouter = require("./routes/occupantdurationsetting");
var staffhousehistoryRouter = require("./routes/staffhousehistory");
var areaRouter = require("./routes/area");
var areadeployemployeeRouter = require("./routes/areadeployemployee");
var teamleadapprovedholidayRouter = require("./routes/teamleadapprovedholiday");
var teamleadrejectholidayRouter = require("./routes/teamleadrejectholiday");
var teamleadrdotRouter = require("./routes/teamleadrdot");
var teamleadrejectrdotRouter = require("./routes/teamleadrejectrdot");
var suggestionRouter = require("./routes/suggestion");
var suggestionareaRouter = require("./routes/suggestionarea");
var suggestionquestionRouter = require("./routes/suggestionquestion");
var sessionRouter = require("./routes/session");
var adjournementRouter = require("./routes/adjournement");
var adjournement_payRouter = require("./routes/adjournement_pay");
var eportaldtr = require("./routes/eportaldtr");
var teamleadapprovedotmealRouter = require("./routes/teamleadapprovedotmeal");
var eportalobRouter = require("./routes/eportalob");
var eportalundertime = require("./routes/eportalundertime");
var teamleadmanualotmealRouter = require("./routes/teamleadmanualotmeal");
var teamleadobRouter = require("./routes/teamleadob");
var teamleadobappliedRouter = require("./routes/teamleadobapplied");
var teamleadobapproveRouter = require("./routes/teamleadobapprove");
var official_business_request_activityRouter = require("./routes/official_business_request_activity");

//#endregion


const verifyJWT = require("./middleware/authenticator");

var app = express();

SetMongo(app);

// view engine setup
app.set("views", path.join(__dirname, "views"));
app.set("view engine", "ejs");

app.use(morgan("dev"));
app.use(express.json());
app.use(express.urlencoded({ limit: "50mb", extended: true, parameterLimit: 500000 }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, "public")));
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocs));

app.use((req, res, next) => {
  eventlogger(req, res, next);
});

//#region ROUTES USE

app.use("/", loginlayoutRouter);
app.use("/access", accessRouter);
app.use("/mobile-api", mobileAPIRouter);
app.use("/forgotpassword", forgotpasswordRouter);
app.use("/applicant_registration", applicant_registrationRouter);
app.use("/session", sessionRouter);
app.use("/register", registerRouter);
app.use("/ojtlogin", ojtloginRouter);
app.use(verifyJWT);
app.use("/index", indexRouter);
app.use("/users", usersRouter);
app.use("/employee", employeeRouter);
app.use("/employeeprofile", employeeprofileRouter);
app.use("/department", departmentRouter);
app.use("/allleave", allleaveRouter);
app.use("/pendingleave", pendingleaveRouter);
app.use("/approvedleave", approvedleaveRouter);
app.use("/rejectedleave", rejectedleaveRouter);
app.use("/attendance", attendanceRouter);
app.use("/shift", shiftRouter);
app.use("/position", positionRouter);
app.use("/disciplinary", disciplinaryRouter);
app.use("/disciplinaryaction", disciplinaryactionRouter);
app.use("/offenses", offensesRouter);
app.use("/violation", violationRouter);
app.use("/healthrecord", healthrecordRouter);
app.use("/govermentid", govermentidRouter);
app.use("/performance", performanceRouter);
app.use("/holiday", holidayRouter);
app.use("/holidayrate", holidayrateRouter);
app.use("/ojt", ojtRouter);
app.use("/announcement", announcementRouter);
app.use("/settings", settingsRouter);
app.use("/eportalsettings", eportalsettingsRouter);
app.use("/salary", salaryRouter);
app.use("/deduction", deductionRouter);
app.use("/requestcashadvance", requestcashadvanceRouter);
app.use("/resigned", resignedRouter);
app.use("/eportalindex", eportalindexRouter);
app.use("/eportalrequestleave", eportalrequestleaveRouter);
app.use("/eportaldisciplinaryaction", eportaldisciplinaryactionRouter);
app.use("/eportalprofile", eportalprofileRouter);
app.use("/eportalsalary", eportalsalaryRouter);
app.use("/eportalcashadvance", eportalcashadvanceRouter);
app.use("/eportalcoop", eportalcoopRouter);
app.use("/eportalpayslip", eportalpayslipRouter);
app.use("/eportalattendance", eportalattendancelayoutRouter);
app.use("/login", loginlayoutRouter);
app.use("/candidate", candidateRouter);
app.use("/loan", loanRouter);
app.use("/payment", paymentRouter);
app.use("/interest", interestRouter);
app.use("/deposit", depositRouter);
app.use("/member", memberRouter);
app.use("/ojtuser", ojtuserRouter);
app.use("/geofencesettings", geofencesettingsRouter);
app.use("/salaryhistory", salaryhistoryRouter);
app.use("/payslip", payslipRouter);
app.use("/generatepayroll", generatepayrollRouter);
app.use("/apprentice", apprenticeRouter);
app.use("/ojtindex", ojtindexRouter);
app.use("/ojtattendance", ojtattendanceRouter);
app.use("/ojtprofile", ojtprofileRouter);
app.use("/ojtreqabsent", ojtreqabsentRouter);
app.use("/attendanceojt", attendanceojtRouter);
app.use("/appsdetails", appsdetailsRouter);
app.use("/otapproval", otapprovalRouter);
app.use("/healthcarddeductions", healthcarddeductionsRouter);
app.use("/healthcarddeductionsID", healthcarddeductionsIDRouter);
app.use("/attendancerequest", attendancerequestRouter);
app.use("/eportalrequestattendance", eportalrequestattendanceRouter);
app.use("/setpayrolldate", setsetpayrolldateRouter);
app.use("/eportalrequestovertime", eportalrequestovertimeRouter);
app.use("/teamleadindex", teamleadindexRouter);
app.use("/teamleadlogin", teamleadloginRouter);
app.use("/teamleademployee", teamleademployeeRouter);
app.use("/teamleadcoa", teamleadcoaRouter);
app.use("/teamleadovertime", teamleadovertimeRouter);
app.use("/teamleadleave", teamleadleaveRouter);
app.use("/teamleadusers", teamleadusersRouter);
app.use("/teamleadpendingcoa", teamleadpendingcoaRouter);
app.use("/teamleadapprovedcoa", teamleadapprovedcoaRouter);
app.use("/teamleadappliedovertime", teamleadappliedovertimeRouter);
app.use("/teamleadapprovedovertime", teamleadapprovedovertimeRouter);
app.use("/teamleadpendingleave", teamleadpendingleaveRouter);
app.use("/teamleadapprovedleave", teamleadapprovedleaveRouter);
app.use("/teamleadgeofence", teamleadgeofenceRouter);
app.use("/teamleadattendance", teamleadattendanceRouter);
app.use("/shiftsettings", shiftsettingsRouter);
app.use("/empbackground", empbackgroundRouter);
app.use("/leavesettings", leavesettingsRouter);
app.use("/approval_stage_settings", approval_stage_settingsRouter);
app.use("/request_approval_settings", request_approval_settingsRouter);
app.use("/subgroup", subgroupRouter);
app.use("/attendance_request_activity", attendance_request_activityRouter);
app.use("/leave_request_activity", leave_request_activityRouter);
app.use("/accessroutelayout", accessroutelayoutRouter);
app.use("/bank", bankRouter);
app.use("/bankaccount", bankaccountRouter);
app.use("/overtime_request_activity", overtime_request_activityRouter);
app.use("/supervisoruser", supervisoruserRouter);
app.use("/change_shift", change_shiftRouter);
app.use("/eportalotmeal", eportalotmealRouter);
app.use("/payroll_adjustments", payroll_adjustmentsRouter);
app.use("/teamleadappliedotmeal", teamleadappliedotmealRouter);
app.use("/meal_request_activity", meal_request_activityRouter);
app.use("/teamleadshift", teamleadshiftRouter);
app.use("/teamleadshiftadjustment", teamleadshiftadjustmentRouter);
app.use("/gov_loans", gov_loansRouter);
app.use("/teamleadsettings", teamleadsettingsRouter);
app.use("/trainings", trainingsRouter);
app.use("/sidebar", sidebarRouter);
app.use("/medecines", medecinesRouter);
app.use("/medecines_request", medecinesrequestRouter);
app.use("/exam", examRouter);
app.use("/question_type", question_typeRouter);
app.use("/question", questionRouter);
app.use("/rating", ratingRouter);
app.use("/teamleadgeofenceemp", teamleadgeofenceempRouter);
app.use("/eportalrequestholiday", eportalrequestHolidayRouter);
app.use("/teamleadholiday", teamleadholidayRouter);
app.use("/teamleadtotalholiday", teamleadtotalholidayRouter);
app.use("/holiday_request_activity", holiday_request_activityRouter);
app.use("/loan_type", loan_typeRouter);
app.use("/employer_contribution", employer_contributionRouter);
app.use("/sudden_deductions", sudden_deductionsRouter);
app.use("/generate13thmonth", generate13thmonthRouter);
app.use("/usersubgroup", usersubgrouplayoutRouter);
app.use("/eportalgovloans", eportalgovloansRouter);
app.use("/enrolled_bank_acc", enrolled_bank_accRouter);
app.use("/eportalrestdayot", eportalrestdayotRouter);
app.use("/restdayot_request_activity", restdayot_request_activityRouter);
app.use("/teamleadappliedrdot", teamleadappliedrdotRouter);
app.use("/teamleadapprovedrdot", teamleadapprovedrdotRouter);
app.use("/retropay", retropayRouter);
app.use("/staffhouse", staffhouseRouter);
app.use("/staffhouseoccupant", staffhouseoccupantRouter);
app.use("/occupantdurationsetting", occupantdurationsettingRouter);
app.use("/staffhousehistory", staffhousehistoryRouter);
app.use("/area", areaRouter);
app.use("/areadeployemployee", areadeployemployeeRouter);
app.use("/teamleadapprovedholiday", teamleadapprovedholidayRouter);
app.use("/teamleadrejectholiday", teamleadrejectholidayRouter);
app.use("/teamleadrdot", teamleadrdotRouter);
app.use("/teamleadrejectrdot", teamleadrejectrdotRouter);
app.use("/suggestion", suggestionRouter);
app.use("/suggestionarea", suggestionareaRouter);
app.use("/suggestionquestion", suggestionquestionRouter);
app.use("/adjournement", adjournementRouter);
app.use("/adjournement_pay", adjournement_payRouter);
app.use("/eportaldtr", eportaldtr);
app.use("/teamleadapprovedotmeal", teamleadapprovedotmealRouter);
app.use("/eportalob", eportalobRouter);
app.use("/eportalundertime", eportalundertime);
app.use("/teamleadmanualotmeal", teamleadmanualotmealRouter);
app.use("/teamleadob", teamleadobRouter);
app.use("/teamleadobapplied", teamleadobappliedRouter);
app.use("/teamleadobapprove", teamleadobapproveRouter);
app.use("/obactivity", official_business_request_activityRouter);

//#endregion


// catch 404 and forward to error handler
app.use(function (req, res, next) {
  next(createError(404));
});

// error handler
app.use(function (err, req, res, next) {
  // set locals, only providing error in development
  res.locals.message = err.message;
  res.locals.error = req.app.get("env") === "development" ? err : {};
  logger.error(err);
  // // render the error page
  res.status(err.status || 500);
  res.render("error");
});

module.exports = app;
