const Payroll = {
  daily_allowance: {
    tablename: "daily_allowance",
    prefix: "da_",
    insertColumns: [
      "employee_id",
      "amount",
      "status",
      "create_by",
      "create_date",
    ],
    selectColumns: [
      "da_id",
      "da_employee_id",
      "da_amount",
      "da_status",
      "da_create_by",
      "da_create_date",
    ],
    selectOptionColumns: {
      id: "da_id",
      employee_id: "da_employee_id",
      amount: "da_amount",
      status: "da_status",
      create_by: "da_create_by",
      create_date: "da_create_date",
    },
  },
  fix_allowance: {
    tablename: "fix_allowance",
    prefix: "fa_",
    insertColumns: [
      "employeeid",
      "amount",
      "cut_off",
      "status",
      "create_by",
      "create_date",
    ],
    selectColumns: [
      "fa_id",
      "fa_employeeid",
      "fa_amount",
      "fa_cut_off",
      "fa_status",
      "fa_create_by",
      "fa_create_date",
    ],
    selectOptionColumns: {
      id: "fa_id",
      employeeid: "fa_employeeid",
      amount: "fa_amount",
      cut_off: "fa_cut_off",
      status: "fa_status",
      create_by: "fa_create_by",
      create_date: "fa_create_date",
    },
  },
};
